{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "1d787b46-a653-41f6-9342-e99c4853b112",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import subprocess"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "c5e4f854-89ad-4265-8fb0-fd534038132b",
   "metadata": {},
   "outputs": [],
   "source": [
    "work_dir = \"/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir\"\n",
    "cluster_idx = 0 #cluster[\"cluster_idx\"]\n",
    "dataset_path = os.path.join(work_dir, \"mapping\", \"cluster_{:06d}\".format(cluster_idx))\n",
    "\n",
    "opensfm_bin = \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "1d32cca8-a780-49dc-8587-891c7cba9933",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "CompletedProcess(args=['/pvextractor/extractor/mapping/OpenSfM/bin/opensfm', 'extract_metadata', '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000'], returncode=0)"
      ]
     },
     "execution_count": 74,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "subprocess.run([opensfm_bin, \"extract_metadata\", dataset_path])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "5f2d76b3-0668-424b-ad30-4053ac9bf31d",
   "metadata": {},
   "outputs": [],
   "source": [
    "tasks = [\n",
    "    \"opensfm_extract_metadata\",\n",
    "    \"opensfm_detect_features\",\n",
    "    \"opensfm_match_features\",\n",
    "    \"opensfm_create_tracks\",\n",
    "    \"opensfm_reconstruct\",\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "8bc524c6-0cf4-4a11-8c5f-92301f87288e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/pvextractor/extractor/mapping/OpenSfM/bin/opensfm extract_metadata \"/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000\" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm detect_features \"/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000\" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm match_features \"/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000\" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm create_tracks \"/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000\" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm reconstruct \"/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000\"'"
      ]
     },
     "execution_count": 69,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "opensfm_commands = []\n",
    "for task in tasks:\n",
    "    if task[:7] == \"opensfm\":\n",
    "        opensfm_commands.append(f'{opensfm_bin} {task[8:]} \"{dataset_path}\"')\n",
    "opensfm_commands = \" && \".join(opensfm_commands)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "e9addfc7-4f1d-4b9b-ad8f-f938b5805307",
   "metadata": {},
   "outputs": [],
   "source": [
    "p = subprocess.run(opensfm_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "id": "9ea3e3ee-c728-479c-9d48-b42d35f0de8b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/extract_metadata.py\", line 11, in run_impl\n",
      "    extract_metadata.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/extract_metadata.py\", line 51, in run_dataset\n",
      "    data.save_camera_models(camera_models)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 798, in save_camera_models\n",
      "    with self.io_handler.open_wt(self._camera_models_file()) as fout:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1292, in open_wt\n",
      "    return cls.open(path, \"w\", encoding=\"utf-8\")\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/camera_models.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/detect_features.py\", line 11, in run_impl\n",
      "    detect_features.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/detect_features.py\", line 28, in run_dataset\n",
      "    max_queue_size, int(expected_mb / average_image_size(data))\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/detect_features.py\", line 76, in average_image_size\n",
      "    for camera in data.load_camera_models().values():\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 792, in load_camera_models\n",
      "    with self.io_handler.open_rt(self._camera_models_file()) as fin:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1296, in open_rt\n",
      "    return cls.open(path, \"r\", encoding=\"utf-8\")\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/camera_models.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/match_features.py\", line 11, in run_impl\n",
      "    match_features.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/match_features.py\", line 14, in run_dataset\n",
      "    pairs_matches, preport = matching.match_images(data, {}, images, images)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/matching.py\", line 43, in match_images\n",
      "    config_override,\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/pairs_selection.py\", line 396, in match_candidates_from_metadata\n",
      "    data.invent_reference_lla()\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 765, in invent_reference_lla\n",
      "    self.save_reference_lla(reference)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 769, in save_reference_lla\n",
      "    with self.io_handler.open_wt(self._reference_lla_path()) as fout:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1292, in open_wt\n",
      "    return cls.open(path, \"w\", encoding=\"utf-8\")\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/reference_lla.json'\n",
      "2021-08-10 14:14:17,839 INFO: reading features\n",
      "2021-08-10 14:14:17,839 DEBUG: Merging features onto tracks\n",
      "2021-08-10 14:14:17,839 DEBUG: Good tracks: 0\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/create_tracks.py\", line 11, in run_impl\n",
      "    create_tracks.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/create_tracks.py\", line 27, in run_dataset\n",
      "    data.save_tracks_manager(tracks_manager)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 695, in save_tracks_manager\n",
      "    with self.io_handler.open(self._tracks_manager_file(filename), \"w\") as fw:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/tracks.csv'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/reconstruct.py\", line 11, in run_impl\n",
      "    reconstruct.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/reconstruct.py\", line 8, in run_dataset\n",
      "    tracks_manager = data.load_tracks_manager()\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 686, in load_tracks_manager\n",
      "    with self.io_handler.open(self._tracks_manager_file(filename), \"r\") as f:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/tracks.csv'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/extract_metadata.py\", line 11, in run_impl\n",
      "    extract_metadata.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/extract_metadata.py\", line 51, in run_dataset\n",
      "    data.save_camera_models(camera_models)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 798, in save_camera_models\n",
      "    with self.io_handler.open_wt(self._camera_models_file()) as fout:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1292, in open_wt\n",
      "    return cls.open(path, \"w\", encoding=\"utf-8\")\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/camera_models.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/detect_features.py\", line 11, in run_impl\n",
      "    detect_features.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/detect_features.py\", line 28, in run_dataset\n",
      "    max_queue_size, int(expected_mb / average_image_size(data))\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/detect_features.py\", line 76, in average_image_size\n",
      "    for camera in data.load_camera_models().values():\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 792, in load_camera_models\n",
      "    with self.io_handler.open_rt(self._camera_models_file()) as fin:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1296, in open_rt\n",
      "    return cls.open(path, \"r\", encoding=\"utf-8\")\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/camera_models.json'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/match_features.py\", line 11, in run_impl\n",
      "    match_features.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/match_features.py\", line 14, in run_dataset\n",
      "    pairs_matches, preport = matching.match_images(data, {}, images, images)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/matching.py\", line 43, in match_images\n",
      "    config_override,\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/pairs_selection.py\", line 396, in match_candidates_from_metadata\n",
      "    data.invent_reference_lla()\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 765, in invent_reference_lla\n",
      "    self.save_reference_lla(reference)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 769, in save_reference_lla\n",
      "    with self.io_handler.open_wt(self._reference_lla_path()) as fout:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1292, in open_wt\n",
      "    return cls.open(path, \"w\", encoding=\"utf-8\")\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/reference_lla.json'\n",
      "2021-08-10 14:14:23,632 INFO: reading features\n",
      "2021-08-10 14:14:23,633 DEBUG: Merging features onto tracks\n",
      "2021-08-10 14:14:23,633 DEBUG: Good tracks: 0\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/create_tracks.py\", line 11, in run_impl\n",
      "    create_tracks.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/create_tracks.py\", line 27, in run_dataset\n",
      "    data.save_tracks_manager(tracks_manager)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 695, in save_tracks_manager\n",
      "    with self.io_handler.open(self._tracks_manager_file(filename), \"w\") as fw:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/tracks.csv'\n",
      "Traceback (most recent call last):\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/bin/opensfm_main.py\", line 16, in <module>\n",
      "    commands.opensfm_commands, create_default_dataset, dataset_choices=[\"opensfm\"]\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command_runner.py\", line 38, in command_runner\n",
      "    command.run(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/command.py\", line 12, in run\n",
      "    self.run_impl(data, args)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/commands/reconstruct.py\", line 11, in run_impl\n",
      "    reconstruct.run_dataset(dataset)\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/actions/reconstruct.py\", line 8, in run_dataset\n",
      "    tracks_manager = data.load_tracks_manager()\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/dataset.py\", line 686, in load_tracks_manager\n",
      "    with self.io_handler.open(self._tracks_manager_file(filename), \"r\") as f:\n",
      "  File \"/pvextractor/extractor/mapping/OpenSfM/opensfm/io.py\", line 1288, in open\n",
      "    return open(*args, **kwargs)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/storage-2/pvextractor-georeferencing/20210510_Schmalenbach/workdir/mapping/cluster_000000/tracks.csv'\n"
     ]
    }
   ],
   "source": [
    "proc1 = subprocess.Popen(opensfm_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n",
    "for line in proc1.stdout:\n",
    "    sys.stdout.write(line)\n",
    "    \n",
    "proc2 = subprocess.Popen(opensfm_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n",
    "for line in proc2.stdout:\n",
    "    sys.stdout.write(line)\n",
    "    \n",
    "#proc.wait()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c828a276-7cd1-4969-9ce1-a1a337be98d7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
